### ISSUE TITLE
Source for TTC Funding Data

### ISSUE THREAD

**Issue by Shafquat** [Nate-Wessel/TTC-funding#1]
This isn't really an issue, just didn't know how else to reach you. A potential source for TTC Funding is the [City of Toronto operating budgets](https://open.toronto.ca/dataset/budget-operating-budget-program-summary-by-expenditure-category/). I'm currently working on consolidating the files into one sheet. Can provide it to you in case you're interested regarding the TTC.

**Comment by Nate-Wessel** [comment]
Please do share - that would be very helpful! What years are you working with? Looks like 2011-2019?
Thanks!

**Comment by Shafquat** [comment]
It's actually from 2010-2019 since 2011's file had 2010 budget data in it as well.
Here's the [compiled list.](https://github.com/Shafquat/D3_budget_viz/blob/master/budget_2010_2019.csv) I haven't gotten around to merging similar programs/categories as of yet, but the 2 TTC specific programs should be good for you to use. Let me know if you catch anything! I had to use a mix of python and some manual efforts to consolidate the data.

**Comment by Nate-Wessel** [comment]
Thanks! I'll have a look and let you know if anything disagrees with my other sources. I hadn't found a source for 2019 yet so this is good.
